
     <h2 class="text-center">Choisissez un article à ajouter au panier</h2>

     <div class="row mt-3">
          <?php foreach($articles as $article): ?>
               <div class="card col-4 mx-1">
                    <div class="w-100">
                         <img class="img-fluid" src="public/img/article/clavier.jpeg"alt="Card image cap"> 
                    </div>
                    
                    <div class="card-body">
                         <h5 class="card-title"><?= $article->getLibelle() ?></h5>
                         <p class="card-text"><?= $article->getDescription() ?>.</p>
                         <p class="card-text">Prix : <?= $article->getPrix() ?></p>
                         <a href="?action=toShopping&id=<?= $article->getId() ?>" class="btn btn-primary">Ajouter au panier</a>
                    </div>
               </div>
          <?php endforeach; ?>
     </div>

