<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
     
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">

     <link rel="stylesheet" href="public/css/style.css">

     <title>Magasin</title>
</head>
<body>

     <header class="bg-primary text-center p-3">
          <h1 class="text-center mb-3">
               <a href="." class="text-white">Magasin en ligne</a>
          </h1>

          <nav>

               <?php if( isset($_SESSION['user']) ): ?>
                    <a href="?action=ajouter" class="btn btn-success">
                         Ajouter article
                    </a>

                    <a href="?action=deconnexion" class="btn btn-danger">
                         Deconnexion
                    </a>

                    <a id="panier" href="?action=deconnexion" class="text-dark">
                         <i class="fa-solid fa-cart-shopping border border-3 rounded-circle p-3">
                              <!-- test si connecté -->
                              <span class="text-secondary">0</span>
                         </i>
                    </a>

               <?php else: ?>
      
               <a href="?action=inscription" class="btn btn-success" >Inscription</a>
               <a href="?action=connexion" class="btn btn-success">Connexion</a>

               <?php endif; ?>
          </nav>
          <div class="text-end">
               <?= isset($_SESSION['user']) ? unserialize($_SESSION['user'])->getPrenom() : '' ?>
          </div>
     </header>

     <main class="container">  
          <?= $content ?? 'pas de vue'; ?>
     </main>

     <footer class="bg-primary text-white text-center p-3 mt-5">
          <a href="" class="text-white text-decoration-none">mentions légales</a>
          <a href="" class="text-white text-decoration-none">Conditions générales de ventes</a>

          <?php
               unset($_SESSION['errors']);
          ?>

     </footer>
     
</body>
</html>