<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
     
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <title>Blog</title>
</head>
<body>

     <header class="text-center bg-dark p-5 text-white mb-3">
          
          <?php if( $userModel->isConnected()): ?>
               <?php if( $userModel->isAdmin() ): ?>
                    <a href="?action=new_user" class="btn btn-success">Ajouter user</a>
                    <a href="?action=new_voiture" class="btn btn-success">Ajouter Voiture</a>
               <?php endif; ?>

               <a href="?action=deconnexion" class="btn btn-danger">Deconnexion</a>
               <div> Bonjour <?= unserialize($_SESSION['user'])->getPrenom() ?> </div>
          <?php else: ?>
               <a href="?action=inscription" class="btn btn-success">Inscription</a>
               <a href="?action=connexion" class="btn btn-success">Connexion</a>
          <?php endif; ?>
     </header>
     <main class="container-fluid">
     