
     <h2>Inscription</h2>

     <form action="" method="post">
          <div class="form-group">
               <input type="radio" id="femme" name="sexe" value="femme">
               <label for="femme">Femme</label>
          </div>
          <div class="form-group">
               <input type="radio" id="homme" name="sexe" value="homme">
               <label for="homme">Homme</label>
          </div>
          <div class="form-group">
               <label for="">Prénom</label>
               <input type="text" name="prenom" class="form-control">
          </div>
          <div class="form-group">
               <label for="">Nom</label>
               <input type="text" name="nom" class="form-control">
          </div>
          <div class="form-group">
               <label for="">Login</label>
               <input type="text" name="login" class="form-control">
          </div>
          <div class="form-group">
               <label for="">Mot de passe</label>
               <input type="password" name="mdp" class="form-control">
          </div>

          <input type="submit" class="btn btn-success mt-3">
     </form>