
<h2>Inscription</h2>

<form action="" method="post">
    
     <div class="form-group">
          <label for="">Marque</label>
          <input type="text" name="marque" class="form-control">
     </div>
     <div class="form-group">
          <label for="">Prix</label>
          <input type="number" name="prix" class="form-control">
     </div>

     <label for="">Proprio</label>
     <select name="proprio" id="" class="form-select">
          <?php foreach($users as $user): ?>
               <option value="<?= $user->getId() ?>"><?= $user->getPrenom() ?></option>
          <?php endforeach; ?>
          </select>

     <input type="submit" class="btn btn-success mt-3">
</form>