
     <h2 class="text-center">liste de clients</h2>

     <table class="table table-striped">
          <tr class="table-dark">
               <td>Id</td>
               <td>Sexe</td>
               <td>Prénom</td>
               <td>Nom</td>
               <td>Login</td>
               <td>rôle</td>
               <td>Action</td>
          </tr>

          <?php foreach($users as $user): ?>
               <tr>
                    <td> <?= $user->getId(); ?> </td>
                    <td> <?= $user->getSexe(); ?> </td>
                    <td> <?= $user->getPrenom(); ?> </td>
                    <td> <?= $user->getNom(); ?> </td>
                    <td> <?= $user->getLogin(); ?> </td>
                    <td> <?= $user->getRole(); ?> </td>
                    <td> 
                         X | U
                    </td>
               </tr>
          <?php endforeach; ?>

     </table>
