
<h2>Connexion</h2>

<form action="" method="post">
    
     <div class="form-group">
          <label for="">Login</label>
          <input type="text" name="login" class="form-control" value="rhalt">
     </div>
     <div class="form-group">
          <label for="">Mot de passe</label>
          <input type="password" name="mdp" class="form-control" value="rhalt">
     </div>

     <input type="submit" class="btn btn-success mt-3">
</form>