<?php ob_start(); ?>

     <table class="table table-striped mt-3">
          <tr class="table-dark">
               <td>Id </td>
               <td>Civilité</td>
               <td>Nom</td>
               <td>Prénom</td>
               <td>Pseudo</td>
               <td>Email</td>
               <td>statut</td>
               <td>Date enregistrement</td>
               <td>Action</td>
          </tr>

          <?php foreach($membres as $membre): ?>
               <tr>
                    <td> <?= $membre->getId_membre() ?> </td>
                    <td> <?= $membre->getCivilite() ?> </td>
                    <td> <?= $membre->getNom() ?> </td>
                    <td> <?= $membre->getPrenom() ?> </td>
                    <td> <?= $membre->getPseudo() ?> </td>
                    <td> <?= $membre->getEmail() ?> </td>
                    <td> <?= $membre->getStatut() ?> </td>
                    <td> <?= $membre->getDate_enregistrement() ?> </td>
                    <td>
                         <a href="?action=modifier&id=<?= $membre->getId_membre() ?>"><i class="fas fa-pen"></i></a>
                         &nbsp; - &nbsp;
                         <a href="?action=supprimer&id=<?= $membre->getId_membre() ?>"><i class="fas fa-trash"></i></a>
                    </td>
               </tr>
          <?php endforeach; ?>

     </table>

     <form action="" method="post">
          <input type="hidden" name="id_membre" value="<?= isset($membreActuel) ? $membreActuel->getId_membre() : 0 ?>">
          <div class="row">
               <div class="col-6 mt-4">
                    <label for="civilte">Civilité</label>
                    <select name="civilite" class="form-select">
                        <option value="homme" <?= isset($membreActuel) && $membreActuel->getCivilite() == 'homme' 
                         ? 'selected' 
                         : '' ?>>homme</option>
                        <option value="femme" <?= isset($membreActuel) && $membreActuel->getCivilite() == 'femme' 
                         ? 'selected' 
                         : '' ?>>femme</option>
                    </select>
                </div>
               <div class="col-6 mt-4">
                   <label for="pseudo">Pseudo</label>
                   <input type="text" name="pseudo" class="form-control" value="<?= isset($membreActuel) ? $membreActuel->getPseudo() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="email">Votre email</label>
                   <input type="email" name="email" class="form-control" value="<?= isset($membreActuel) ? $membreActuel->getEmail() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="mdp">Mot de passe</label>
                   <input type="password" name="mdp" class="form-control" >
               </div>
               <div class="col-6 mt-4">
                   <label for="nom">Votre nom</label>
                   <input type="text" name="nom" class="form-control" value="<?= isset($membreActuel) ? $membreActuel->getNom() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="prenom">Votre prénom</label>
                   <input type="text" name="prenom" class="form-control" value="<?= isset($membreActuel) ? $membreActuel->getPrenom() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="statut">statut</label>
                   <select name="statut" class="form-select">
                       <option value="0" <?= isset($membreActuel) && $membreActuel->getStatut() == '0' 
                         ? 'selected' 
                         : '' ?> >membre</option>
                       <option value="1" <?= isset($membreActuel) && $membreActuel->getStatut() == '1' 
                         ? 'selected' 
                         : '' ?>>admin</option>
                   </select>
               </div>          
           </div>
           <input type="submit" class="btn btn-success mt-3">
     </form>

<?php
$content = ob_get_clean();

include "views/template.phtml";