
<form action="" method="post">
     <div class="row">
         <div class="col-6 mt-4">
             <label for="pseudo">Libelle</label>
             <input type="text" name="libelle" class="form-control" placeholder="libelle" >
             
         </div>
         <div class="col-6 mt-4">
             <label for="email">Prix</label>
             <input type="number" name="prix" class="form-control" placeholder="prix" >
         </div>
         <div class="col-6 mt-4">
             <label for="mdp">Quantité</label>
             <input type="number" name="quantite" class="form-control" placeholder="quantité">
         </div>
 
         <div class="col-6 mt-4">
             <label for="prenom">Image</label>
             <input type="text" name="image" class="form-control" placeholder="logo">
            
         </div>   
         <div class="col-6 mt-4">
             <label for="prenom">Catégorie</label>
             <input type="text" name="categorie" class="form-control" placeholder="Catégorie">
         </div>   
         
         <div class="col-6 mt-4">
          <label for="nom">Description</label>
          <textarea name="description" id="" cols="30" rows="10" class="form-control"></textarea>
      </div> 
           
     </div>
     <input type="submit" class="btn btn-success mt-3">
 </form>
