<h2 class="text-center">Ajouter au panier</h2>

     <div class="row mt-3">
         
               <div class="card col-4 mx-1">
                    <div class="w-100">
                         <img class="img-fluid" src="public/img/article/clavier.jpeg"alt="Card image cap"> 
                    </div>
                    
                    <div class="card-body">
                         <h5 class="card-title"><?= $article->getLibelle() ?></h5>
                         <p class="card-text"><?= $article->getDescription() ?></p>
                         <p class="card-text">Prix : <?= $article->getPrix() ?></p>

                         <p class="card-text">Quantité dispo : <?= $article->getQuantite() ?></p>
                         
                    </div>
               </div>

               <div class="col-5">
                    <form action="">
                         <input type="number" name="quantite" value="1" size="2">
                         <input type="hidden" name="article" value="<?= $article->getId() ?>" size="2">
                         <input type="submit" class="btn btn-success mt-3" value="Ajouter au panier">
                    </form>
               </div>
        
     </div>