<?php ob_start(); ?>

     <div class="row mt-3">
          <?php foreach($vehicules as $vehicule): ?>
               <div class="card col-3 mx-1">
                    <div class="w-75">
                         <img class="img-fluid" src="public/img/vehicule/<?= $vehicule->getPhoto() ?>"alt="Card image cap"> 
                    </div>
                    
                    <div class="card-body">
                         <h5 class="card-title"><?= $vehicule->getTitre() ?></h5>
                         <p class="card-text"><?= $vehicule->getDescription() ?>.</p>
                         <p class="card-text">Prix : <?= $vehicule->getPrix_journalier() ?>/jour</p>
                         <a href="?actionCmd=reserver&vehicule=<?= $vehicule->getId_vehicule() ?>" class="btn btn-primary">Réserver</a>
                    </div>
               </div>
          <?php endforeach; ?>
     </div>
<?php

$content = ob_get_clean();

include "template.phtml";